application:
  version: 1.0.0-SNAPSHOT
  date: 03.03.2025
  application-code: 1856
  
server:
  servlet:
    contextPath: /gamma-project
    
gamma:
  platform:
    authentication-url:
    message-url:
    sign-url:
    login-url:

spring:
  kafka:
    producer:
      bootstrap-servers: server-url:8080
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    template:
      message-topic: message-topic
      log-topic: log-topic
